apiVersion: v1
kind: Service
metadata:
  name: flink-upload-jobmanager
  namespace: flink-upload
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6123
    - name: blob-server
      port: 6124
    - name: webui
      port: 8081
  selector:
    app: flink-upload
    component: jobmanager